name = "vGWAS"
uuid = "9514c204-b736-47c9-8157-11c3e9e5ab30"
authors = ["Seyoon Ko <syko0507@snu.ac.kr> and contributors"]
version = "0.1.0"

[deps]
WiSER = "2ff19380-1883-49fc-9d10-450face6b90c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
